source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

use_frameworks!

platform :ios, '8.0'
inhibit_all_warnings!

project './LMVrDemo.xcodeproj'
workspace '../LMVr.xcworkspace'

target 'LMVrDemo' do
    pod 'LMVr', :path => '../'
end
